#!/bin/bash

CLUSTER_NAME=TestCluster
NUMBER_OF_NODES=3
NUMBER_OF_DC=3

DEFAULT_USER=root

NODE1_HOST=IP_NODE_1
NODE1_DC=DC1
NODE1_RAC=RAC1

NODE2_HOST=IP_NODE_2
NODE2_DC=DC2
NODE2_RAC=RAC1

NODE3_HOST=IP_NODE_3
NODE3_DC=DC3
NODE3_RAC=RAC1

CASSANDRA_ARCHIVE_DIR=/opt/programs/apache-cassandra-1.2.18

DATA_DIRECTORY=/opt/var/clusterDeployment
COMMIT_LOG_DIRECTORY=/opt/var/clusterDeployment

SEEDS=IP_NODE_1

SNITCH=PropertyFileSnitch

INSTALL_DIRECTORY=/opt/programs

PARTITIONER=RandomPartitioner